### PR TITLE
Update postcss to 5.0

### PR DESCRIPTION
**Pull request by avanes**
#4

### CODE REVIEW

**Comment by simonsmith** [comment]
Thanks for this!

**Comment by TrySound** [comment]
Make 1.0.0 release please

**Comment by simonsmith** [comment]
Published 0.3.0, will look to 1.0.0 once #7  & #3 have been addressed. Thanks

**Comment by TrySound** [comment]
@simonsmith Wrong, wrong! postcss 5 api is breaking changes!

**Comment by TrySound** [comment]
@simonsmith I'm sure, you broke a few builds.

**Comment by simonsmith** [comment]
Not breaking changes to the public API of this plugin though... 

> What should I do if I update my own dependencies without changing the public API?

That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it's obviously a minor level increment.

http://semver.org/

**Comment by simonsmith** [comment]
> I'm sure, you broke a few builds.

What do you mean, the old methods `each` have not been removed, just deprecated

**Comment by TrySound** [comment]
@simonsmith But those who use 4.0 with caret dependencies will get 0.3.1 and their build will crash.

**Comment by TrySound** [comment]
@simonsmith And it's not theoretically problem. @seaneking updated postcss-clearfix with patch and all my build were broken.

**Comment by simonsmith** [comment]
Right, I see. That does make sense. Maybe easier to explain that initially rather than "Wrong! Wrong!"

I'll make the correct changes. Thanks

**Comment by TrySound** [comment]
Sorry, I was outraged.)

**Comment by simonsmith** [comment]
1.0.0 published - https://www.npmjs.com/package/postcss-property-lookup

**Comment by jedmao** [comment]
That's why I said it needed a major version bump in #4, but I'm glad it's all sorted now! I supposed I could have added a description of why it needed a major version bump.

**Pull request merged**
