### PR TITLE
Update to PostCSS 8

### PR DESCRIPTION
**Pull request by onigoetz**
Hello,

This PR makes the following changes, fixes #20

* Update this module to PostCSS 8 using the migration guide : https://evilmartians.com/chronicles/postcss-8-plugin-migration
* Update the node version to use 10 at the minimum
* Remove the babel build step
* Replace Jest with Mocha (way less dependencies to install, the advanced features of Jest aren't needed here) 
* Update TypeScript Typings
* Add GitHub Actions

### CODE REVIEW

**Comment by Knagis** [comment]
FYI: https://www.npmjs.com/package/@notiv/postcss-property-lookup an existing fork of this plugin with PostCSS8 support.

**Comment by simonsmith** [comment]
@onigoetz Changes look good. Will merge and release when I get a free moment. Appreciate it

**Comment by simonsmith** [comment]
Only change I'd recommend is using `yarn` and removing the `package-lock.json`.

**Comment by onigoetz** [comment]
Sure can do, I also prefer Yarn I just didn't want to introduce more changes than needed :)

**Comment by onigoetz** [comment]
Oh, I missed that the yarn.lock already existed.
Change done

**Comment by simonsmith** [comment]
It looks like `yarn.lock` has been deleted in the diff?

**Comment by onigoetz** [comment]
Yes it looks like it but actually it's just 2'000 lines shorter. if you load the diff you'll see there is still content.
The main reason is the removal of Babel and Jest.

**Comment by simonsmith** [comment]
Ah sorry, of course. My bad!

**Comment by simonsmith** [comment]
Done - https://github.com/simonsmith/postcss-property-lookup/releases/tag/3.0.0

Thanks @onigoetz

**Pull request merged**
